name: Companies
version: 1.0-SNAPSHOT
main: frostdev.companies.Companies
api-version: 1.13
authors: [MagnusFrost]
description: Compandies Plugin Developed for the HelloMiners Minecraft Server

commands:
  companies:
    description: Main command.
    aliases: [comp]