name: HMDB
version: ALPHA-0.1
main: frostdev.frostdev.HMDB
api-version: 1.13
author: MagnusFrost
description: HelloMiners Database Manager
softdepend: [SQL, Vault]

commands:
  HMDB:
    description: Main command.
    aliases: [hmdb]